name: Hello World Workflow # This is just the workflow name shown in GitHub Actions tab.

on:   # trigger    # Run this workflow when someone pushes code to the main branch.
  push:
    branches:   # git push → main branch → workflow starts
      - main

jobs:  # A job is a group of steps that run together.
  say-hello: # job name 
    runs-on: ubuntu-latest  #This tells GitHub:

                          #                                “Run this job on a Linux machine (Ubuntu).”

    steps: #Steps are commands executed one by one
      - name: Print Hello World
        run: echo "Hello World from GitHub Actions"